import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js";
import { OrbitControls } from "https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/controls/OrbitControls.js";
const q = (s) => document.querySelector(s);
const mount = q("#sceneMount"), loader = q("#sceneLoader"), mode = q("#sceneMode"), hud = q("#gameHud"), reticle = q("#gameReticle"), toast = q("#gameToast");
const scoreEl = q("#scoreValue"), timeEl = q("#timeValue"), comboEl = q("#comboValue"), how = q("#howModal"), result = q("#resultModal"), siteToast = q("#siteToast");
const colors = { navy: 0x081226, clay: 0xb76d4f, clayDark: 0x6f3e43, saffron: 0xef9a4b, gold: 0xf2cf8b, teal: 0x73c8bc, cream: 0xf5ead9, dark: 0x211526 };
let scene, camera, renderer, controls, clock, hero, game, basket, items = [], playing = false, score = 0, combo = 1, peak = 1, offerings = 0, targetX = 0, currentX = 0, endAt = 0, soundOn = false, audio;
const material = (c, r = .5, m = .05, e = 0, ei = 0) => new THREE.MeshStandardMaterial({ color: c, roughness: r, metalness: m, emissive: e, emissiveIntensity: ei });
function add(parent, geo, mat, pos = [0,0,0], scale = [1,1,1]) { const x = new THREE.Mesh(geo, mat); x.position.set(pos[0], pos[1], pos[2]); x.scale.set(scale[0], scale[1], scale[2]); parent.add(x); return x; }
function vinayaka() {
  const g = new THREE.Group(); g.position.set(0, .22, -1.3); const skin = material(0xd08b62, .38), cloth = material(0x963f3c, .5), gold = material(colors.gold, .24, .62, colors.saffron, .2), ruby = material(0xd74b48, .3, .3, 0x5c151b, .15), dark = material(colors.dark, .5);
  const body = new THREE.Group(); body.position.y = .78; g.add(body); add(body, new THREE.SphereGeometry(1.05, 32, 24), skin, [0,0,0], [1,.98,.82]); add(body, new THREE.SphereGeometry(.77, 28, 20), cloth, [0,-.42,.05], [1.18,.48,1]);
  const head = new THREE.Group(); head.position.y = 1.72; body.add(head); add(head, new THREE.SphereGeometry(.78, 32, 24), skin, [0,0,0], [1.04,1.06,.9]);
  [-.75,.75].forEach((x) => add(head, new THREE.SphereGeometry(.54, 24, 16), skin, [x,0,0], [.72,1.04,.28]));
  [-.27,.27].forEach((x) => add(head, new THREE.SphereGeometry(.07, 12, 10), dark, [x,.12,.7], [1,1.3,.5]));
  const trunk = new THREE.Group(); trunk.position.set(0,-.18,.72); trunk.rotation.x = -.12; head.add(trunk); add(trunk, new THREE.CapsuleGeometry(.2,.62,8,18), skin, [0,-.1,0], [1,1,.8]); add(trunk, new THREE.SphereGeometry(.22,18,14), skin, [.16,-.47,.02], [1.1,.75,.82]);
  [-.16,.16].forEach((x) => add(head, new THREE.ConeGeometry(.09,.34,12), material(colors.cream,.35), [x,-.33,.64], [1,1,1]));
  const crown = new THREE.Group(); crown.position.y = .75; head.add(crown); add(crown, new THREE.CylinderGeometry(.55,.78,.22,32), gold); add(crown, new THREE.ConeGeometry(.58,.76,32), gold, [0,.44,0]); add(crown, new THREE.TorusGeometry(.58,.045,8,32), ruby, [0,.1,0]); add(crown, new THREE.SphereGeometry(.1,12,12), ruby, [0,.84,0]);
  const arms = new THREE.CapsuleGeometry(.16,.65,8,14); const a = add(body, arms, skin, [-.75,.18,.03]); a.rotation.z = -.72; const b = add(body, arms, skin, [.75,.18,.03]); b.rotation.z = .72;
  const halo = add(g, new THREE.TorusGeometry(1.54,.035,10,72), gold, [0,1.9,-.16]); halo.userData.halo = true; add(g, new THREE.TorusGeometry(1.35,.014,8,72), material(colors.saffron,.25,.3,colors.saffron,.8), [0,1.9,-.17]);
  const mouse = new THREE.Group(); mouse.position.set(1.25,-.02,.35); g.add(mouse); add(mouse,new THREE.SphereGeometry(.32,20,14),dark,[0,.16,0],[1.25,.85,.85]); add(mouse,new THREE.SphereGeometry(.19,16,12),dark,[.28,.26,.02]); return g;
}
function createWorld() {
  scene = new THREE.Scene(); scene.background = new THREE.Color(colors.navy); scene.fog = new THREE.FogExp2(colors.navy,.045); camera = new THREE.PerspectiveCamera(34,1,.1,100); camera.position.set(0,2.2,9.6); camera.lookAt(0,1.4,0); clock = new THREE.Clock(); renderer = new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.8)); renderer.outputColorSpace = THREE.SRGBColorSpace; renderer.shadowMap.enabled = true; mount.appendChild(renderer.domElement); controls = new OrbitControls(camera,renderer.domElement); controls.enableDamping = true; controls.enablePan = false; controls.minDistance = 6.5; controls.maxDistance = 12; controls.target.set(0,1.35,0);
  scene.add(new THREE.HemisphereLight(0xb9d8ff,0x241728,1.7)); const key = new THREE.DirectionalLight(0xffd8ad,3.2); key.position.set(-4,7,6); key.castShadow = true; scene.add(key); const warm = new THREE.PointLight(0xf39153,10,12,2); warm.position.set(0,2.4,2.5); scene.add(warm); const teal = new THREE.PointLight(0x3ab6ae,5,10,2); teal.position.set(3,2,-1); scene.add(teal);
  const floor = add(scene,new THREE.CircleGeometry(8,64),material(0x0b1528,.78,.12)); floor.rotation.x = -Math.PI/2; const back = add(scene,new THREE.PlaneGeometry(18,10),material(0x101d35,.9),[0,3.6,-3.8]); back.receiveShadow = true; const plinth = add(scene,new THREE.CylinderGeometry(2.8,3.05,.26,64),material(0x302239,.48,.28),[0,.15,-.1]); plinth.castShadow = true; const ring = add(scene,new THREE.TorusGeometry(2.4,.018,8,96),material(colors.gold,.25,.7,colors.gold,.7),[0,.31,-.08]); ring.rotation.x = -Math.PI/2;
  const mandala = new THREE.Group(); mandala.position.set(0,3.35,-3.6); scene.add(mandala); [1.55,1.2,.86].forEach((r) => add(mandala,new THREE.TorusGeometry(r,.014,8,64),material(colors.gold,.3,.2,colors.saffron,.7))); mandala.userData.mandala = true;
  hero = vinayaka(); scene.add(hero); game = new THREE.Group(); game.visible = false; scene.add(game); basket = new THREE.Group(); basket.position.set(0,-.95,1.2); game.add(basket); const bm = material(colors.gold,.28,.35,colors.saffron,.2); const bt = add(basket,new THREE.TorusGeometry(.72,.12,12,32),bm); bt.rotation.x = Math.PI/2; add(basket,new THREE.CylinderGeometry(.78,.58,.16,32,1,true),material(0x9b533e,.54),[0,-.05,0]); add(basket,new THREE.SphereGeometry(.75,20,12),material(colors.saffron,.48),[0,-.12,0],[1,.25,1]);
  resize(); addEventListener("resize",resize); loader.classList.add("is-hidden"); requestAnimationFrame(loop);
}
function resize() { if (!renderer) return; const r = mount.getBoundingClientRect(); renderer.setSize(r.width,r.height,false); camera.aspect = r.width/r.height; camera.updateProjectionMatrix(); }
function item(type) { const g = new THREE.Group(); g.userData.type = type; if (type === "modak") { const m=material(colors.gold,.3,.18,colors.saffron,.2); add(g,new THREE.ConeGeometry(.22,.34,10),m); add(g,new THREE.TorusGeometry(.13,.025,6,12),m,[0,-.08,0]); } else if (type === "flower") { const m=material(colors.saffron,.45,.02,colors.saffron,.3); for(let i=0;i<5;i++){const a=i*Math.PI*2/5;add(g,new THREE.SphereGeometry(.13,10,8),m,[Math.cos(a)*.15,Math.sin(a)*.15,0],[.7,1.2,.4]);} add(g,new THREE.SphereGeometry(.1,10,8),material(colors.gold,.3,.2),[0,0,.08]); } else { const m=material(colors.teal,.55,.02,colors.teal,.2); add(g,new THREE.CapsuleGeometry(.045,.35,5,8),m); add(g,new THREE.CapsuleGeometry(.04,.28,5,8),m,[.1,.04,0],[1,1,.5]).rotation.z=.6; } return g; }
function spawn() { const type = Math.random()<.55?"modak":Math.random()<.78?"flower":"durva"; const g=item(type); g.position.set((Math.random()-.5)*7.2,3.65,.7+Math.random()*.7); g.userData.speed=1.7+Math.random()*.8; g.userData.spin=(Math.random()-.5)*3; game.add(g); items.push(g); }
function begin() { close(how); close(result); playing=true; score=0; combo=1; peak=1; offerings=0; targetX=0; currentX=0; items.forEach((x)=>game.remove(x)); items=[]; endAt=performance.now()+60000; hero.visible=false; game.visible=true; controls.enabled=false; camera.position.set(0,1.5,8.7); camera.lookAt(0,.8,0); hud.classList.add("is-active"); reticle.classList.add("is-active"); mode.textContent="FESTIVAL RUN"; toast.textContent="Bappa bless your run"; toast.classList.add("is-visible"); setTimeout(()=>toast.classList.remove("is-visible"),1200); mount.scrollIntoView({behavior:"smooth",block:"center"}); tone(220,440); }
function finish() { if(!playing)return; playing=false; game.visible=false; hero.visible=true; controls.enabled=true; hud.classList.remove("is-active"); reticle.classList.remove("is-active"); mode.textContent="LIVE SCENE"; const best=Math.max(Number(localStorage.getItem("vighnaharta-best")||0),score); localStorage.setItem("vighnaharta-best",best); q("#resultScore").textContent=String(score).padStart(4,"0"); q("#bestScore").textContent=String(best).padStart(4,"0"); q("#bestCombo").textContent="x"+peak; q("#offeringCount").textContent=offerings; q("#resultRank").textContent=score>=best?"NEW BEST · 01":"BLESSED RUN · KEEP GOING"; open(result); tone(392,784); }
function collect(g) { const pts=g.userData.type==="modak"?100:g.userData.type==="flower"?60:40; score += pts*combo; offerings++; combo=Math.min(8,combo+(g.userData.type==="modak"?1:0)); peak=Math.max(peak,combo); game.remove(g); toast.textContent="+"+(pts*combo); toast.classList.add("is-visible"); setTimeout(()=>toast.classList.remove("is-visible"),450); tone(440,720); }
function update(now,dt) { if(!playing)return; const left=Math.max(0,(endAt-now)/1000); scoreEl.textContent=String(score).padStart(4,"0"); timeEl.textContent="00:"+String(Math.ceil(left)).padStart(2,"0"); comboEl.textContent="x"+combo; reticle.querySelector("span").style.transform="scaleX("+Math.max(.03,left/60)+")"; if(left<=0){finish();return;} if(now%1000<30 && items.length<10)spawn(); currentX += (targetX-currentX)*Math.min(1,dt*11); basket.position.x=currentX; items.forEach((g)=>{g.position.y-=g.userData.speed*dt;g.rotation.y+=g.userData.spin*dt;}); const keep=[]; items.forEach((g)=>{if(Math.abs(g.position.x-currentX)<.9&&g.position.y<-.45&&g.position.y>-1.4){collect(g);}else if(g.position.y< -1.9){if(g.userData.type==="modak")combo=1;game.remove(g);}else keep.push(g);}); items=keep; }
function loop() { requestAnimationFrame(loop); const dt=Math.min(clock.getDelta(),.05), now=performance.now(); update(now,dt); if(hero.visible){hero.rotation.y=Math.sin(now*.00018)*.025; scene.traverse((x)=>{if(x.userData.halo)x.rotation.z+=dt*.18;if(x.userData.mandala)x.rotation.z-=dt*.025;});} controls.update(); renderer.render(scene,camera); }
function open(m){m.classList.add("is-open");m.setAttribute("aria-hidden","false");} function close(m){m.classList.remove("is-open");m.setAttribute("aria-hidden","true");} function tone(a,b){if(!soundOn)return;audio=audio||new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);const n=audio.currentTime;o.frequency.setValueAtTime(a,n);o.frequency.exponentialRampToValueAtTime(b,n+.16);g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(.06,n+.03);g.gain.exponentialRampToValueAtTime(.0001,n+.25);o.start(n);o.stop(n+.27);}
q("#playButton").onclick=()=>open(how); q("#storyPlay").onclick=begin; q("#closingPlay").onclick=begin; q("#modalPlay").onclick=begin; q("#replayButton").onclick=begin; q("#learnButton").onclick=()=>q("#howToPlay").scrollIntoView({behavior:"smooth"}); q("#closeHow").onclick=()=>close(how); q("#soundToggle").onclick=()=>{soundOn=!soundOn;toast.textContent=soundOn?"Sound is on":"Sound is off";toast.classList.add("is-visible");setTimeout(()=>toast.classList.remove("is-visible"),1000);tone(240,300);}; q("#shareButton").onclick=async()=>{const t="I scored "+score+" in Vighnaharta 3D - Festival Quest. Ganapati Bappa Morya!";try{if(navigator.share)await navigator.share({title:"Vighnaharta 3D",text:t,url:location.href});else{await navigator.clipboard.writeText(t);siteToast.textContent="Blessing copied to clipboard";siteToast.classList.add("is-visible");setTimeout(()=>siteToast.classList.remove("is-visible"),2200);}}catch(e){}}; document.querySelectorAll(".modal-backdrop").forEach((m)=>m.onclick=(e)=>{if(e.target===m)close(m);}); addEventListener("keydown",(e)=>{if(!playing)return;if(e.key==="ArrowLeft"||e.key==="a"||e.key==="A")targetX=Math.max(-3.2,targetX-.6);if(e.key==="ArrowRight"||e.key==="d"||e.key==="D")targetX=Math.min(3.2,targetX+.6);}); let down=null; mount.addEventListener("pointerdown",(e)=>{if(playing)down=e.clientX;}); mount.addEventListener("pointermove",(e)=>{if(playing&&down!==null){targetX=Math.max(-3.2,Math.min(3.2,targetX+(e.clientX-down)/mount.clientWidth*6));down=e.clientX;}}); mount.addEventListener("pointerup",()=>down=null); createWorld();
